### PR TITLE
Trim headers fixes #24

### LINKED ISSUE #24: Trim whitespace in csv headers
Sometimes the headers include whitespace like

```
a, b , c,  d
1, 2 ,3 , 4
```

In these cases they shouldn't be parsed as `' b'` but be `' b'.trim()` instead.

### PR DESCRIPTION
**Pull request by finnp**
Hey,

this PR adds trimming headers. There should be probably be an option to enable/disable it, but I'm not sure what the default should be

Best,
Finn

### CODE REVIEW

**Comment by karissa** [comment]
+1

**Comment by mafintosh** [comment]
shouldn't it then trim values as well for consistency?

**Comment by karissa** [comment]
It's expensive to do that, right? it's hard to know if its good to trim the values, whereas for headers its mostly desired

**Comment by hmalphettes** [comment]
`mapHeaders` can do that:
```
csv({mapHeaders: function (header) return header.trim() ) 
```

**Comment by shellscape** [comment]
Going to pass on this PR, citing the use of `mapHeaders`. @finnp thank you for all of your work on this PR.

**Pull request closed without merging**
