### PR TITLE
fix: losing all headers after a broken line

### PR DESCRIPTION
**Pull request by aheissenberger**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [x] yes
- [ ] no

If yes, please describe the breakage.

when amount of columns of cell not equal to amount of headers the object returned is using indexed keys instead of the headers.
old version did only replace headers with index keys when there where more columns. When there where less columns the headers where still used.

### Please Describe Your Changes

Problem #150 

* fix bug which replaced the global variable `this.headers` with indexed header when one line was broken
* changed behavore to be identical for both use cases: less columns, more columns (this is a suggestion)

### CODE REVIEW

**Comment by aheissenberger** [comment]
In an older version of this parser the logic for broken rows did not have any impact on the header mapping. What was the reason to change the behaviour to switch to indexed object if a line is broken?

**Comment by shellscape** [comment]
@aheissenberger that was likely a regression or untested side-effect when the indexed headers were added due to incomplete tests or poor coverage.

**Comment by aheissenberger** [comment]
@shellscape using indexed props for columns with wrong amount of columns broke my code which was based on an older version of css-parser. I changed the code to be more consistent and the headers are now always set except for the case of more columns - here I will use the index for columns with no existing header.

**Comment by SimonSimCity** [comment]
We've encountered the same problem and can confirm that this PR (as it is now) will fix the problem. Currently we're back on `2.3.0` until a version containing this fix is released.

**Comment by nathsimpson** [comment]
@mafintosh  When can this be released?

**Comment by louisgv** [comment]
@shellscape @mafintosh  would love to see this fix merged and published

**Comment by shellscape** [comment]
I won't have time to address any issues or PRs for this project until mid to late January, unfortunately.

**Comment by MalxMalx** [comment]
Hi, don't want to be seen as unpolite, but can you merge this PR? It's already February. I understand that you may have other important things on your table, but this problem affects my project, so I hope it can be fixed soon.

**Comment by SimonSimCity** [comment]
@shellscape if you feel comfortable with the idea, I volunteer for helping you out with this project. I care very much about this project and want it to remain both healthy, in good shape and code-quality.

**Comment by shellscape** [comment]
@MalxMalx that's why it's open source. please use the fork this PR was based on.

@SimonSimCity not up to me unfortunately

**Comment by MalxMalx** [comment]
@shellscape I decided to just use the previous version which doesn't have this issue. Thanks!
As soon as I have enough time, I'll probably migrate to fast-csv as it looks like a better package. Unrelated to this issue, but I've had huge event loop lag with csv-parser (in some cases up to 3-4 seconds), which is disturbing. And judging by how it's maintained, it's probably not fit for serious production systems, unfortunately.

**Comment by joshkay** [comment]
Also looking to have this merged.  Updated this dependency and this bug makes it unusable for me currently.  Downgrading to 2.3.0 where it was originally working for the time being.  @SimonSimCity would love to help you get this merged if possible

**Comment by stefan-jonasson** [comment]
I'm also waiting for this to be merged, anything I can do to help?

**Review by TrySound — APPROVED** [review]

**Pull request merged**
