### PR TITLE
fix: avoid strict validations for skipped rows

### PR DESCRIPTION
**Pull request by RimashMohomed**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [x] yes
- [ ] no

skipped rows skipped using skipLines are not validated against strict option

fixes issue https://github.com/mafintosh/csv-parser/issues/136

### CODE REVIEW

**Comment by RimashMohomed** [comment]
FYI @shellscape

**Comment by shellscape** [comment]
Please don't tag/ping maintainers in replies unless a significant amount of time has passed without review.

You'll need to add a test for this fix for us to accept the changes.

**Comment by RimashMohomed** [comment]
> Please don't tag/ping maintainers in replies unless a significant amount of time has passed without review.
> 
> Thanks for the PR beer You'll need to add a test for this fix for us to accept the changes.

sure will add tests and re submit, anyway contribution link is broken such i couldn't find the requirements for a PR, can you please provide a resource for the completeness criteria for a PR (to avoid the trouble :) )?

**Comment by shellscape** [comment]
Thanks for putting together this PR. It is appreciated. The fix for this was somewhat simpler than what you had submitted. I've committed a fix and tests for it. We'll release this fix later on in the day.

**Pull request closed without merging**
