### PR TITLE
[HOTFIX] process all rows in larger CSV

### LINKED ISSUE #39: CVS parsing stops before end of the file with 1.9.0
Reproduced easily with a CSV from government:
http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_month.csv

```js
var csv   = require('csv-parser')
var fs    = require('fs')
var file  = 'all_month.csv'
var count = 0;

fs.createReadStream(file).pipe(csv())
    .on('data', () => count++)
    .on('finish', () => console.log(count));
```

With 1.8.0: 7303 line read (all of them)
With 1.9.0: 5190 line read

This is a huge issue guys. I cannot investigate right now but you should really add big CSV files to your test suite.

### PR DESCRIPTION
**Pull request by galenandrew**
The issue was with variable scope when tracking if the cell is quoted or not. PR includes sample data file and test.

fixes #39

### CODE REVIEW

**Comment by maxogden** [comment]
correct me if I'm wrong, but the size of the csv in this PR is irrelevant
right? it just happens to contain a failing case on some of the lines?

ideally the cases can be identified and added to csv-spectrum

On Tuesday, December 22, 2015, Andrew Turner <notifications@github.com>
wrote:

> The issue was with variable scope when tracking if the cell is quoted or
> not. PR includes large file test.
>
> fixes #39 <https://github.com/mafintosh/csv-parser/issues/39>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/mafintosh/csv-parser/pull/40
> Commit Summary
>
>    - hotfix support for large files
>
> File Changes
>
>    - *M* index.js
>    <https://github.com/mafintosh/csv-parser/pull/40/files#diff-0> (6)
>    - *A* test/data/large_file.csv
>    <https://github.com/mafintosh/csv-parser/pull/40/files#diff-1> (7269)
>    - *M* test/test.js
>    <https://github.com/mafintosh/csv-parser/pull/40/files#diff-2> (9)
>
> Patch Links:
>
>    - https://github.com/mafintosh/csv-parser/pull/40.patch
>    - https://github.com/mafintosh/csv-parser/pull/40.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mafintosh/csv-parser/pull/40>.
>


-- 
Sent from my phone

**Comment by galenandrew** [comment]
@maxogden, you're correct that the size is irrelevant. I was simply using the example file provided in Issue #39 . The purpose of this PR is purely to fix that issue where the parser does not process all lines in the file.

**Comment by mafintosh** [comment]
thanks for the fix. i agree that we should move the test to csv-spectrum at some point.

**Comment by mafintosh** [comment]
1.9.1

**Comment by vladimirkrasulya-planorama** [comment]
The issue has appeared again in 1.9.2

**Comment by mafintosh** [comment]
@vladimirkrasulya-planorama the tests seem to be passing? are we missing a case?

**Comment by vladimirkrasulya-planorama** [comment]
@mafintosh  I'm sorry - my input file was broken.

**Pull request merged**
