### PR TITLE
Allow options "separator", "quote" and "esscape" to be empty

### PR DESCRIPTION
**Pull request by x3cion**
A little modification allowing said options to be empty. I need this for a ~ 1 million CSV row's read. So it's proven to work. I built a new test for it, too and made sure all other tests are working.

### CODE REVIEW

**Comment by mafintosh** [comment]
just so i understand this feature, this is basically just to disable the escape/quoting parsing right?

**Comment by x3cion** [comment]
Yes. Separators and newline only.

**Comment by x3cion** [comment]
Is anything wrong? Are you testing it? Why aren't you merging?

If you need anything, let me know.

**Comment by emilbayes** [comment]
Why use `''` instead of `null` or `undefined`?

**Comment by x3cion** [comment]
Currently, undefined means default. I didn't want to change the default behaviour.

As far as I see, giving null would now throw an error. I could change it so that any other value than '' would result in default behaviour.

**Comment by shellscape** [comment]
@x3cion under what conditions would separator need to be an empty string?

**Comment by x3cion** [comment]
@shellscape This PR is nearly two years old, I cannot really remember what I thought. of If I think about it now, I guess I might've thought of a single-column-per-line mode. It's not a bad thing to make this possible.

Actually I don't use this parser anymore. I use the fork I created as legacy and build an own csv parser for all other purposes. As I can see, there are conflicts now, too. I can close this PR if you want.

**Comment by shellscape** [comment]
@x3cion OK thanks for the followup. We'll close for now, but if the need comes up again we'll try to merge your branch for the feature.

**Comment by alexvilchis** [comment]
I would like this feature!

**Pull request closed without merging**
