### PR TITLE
Updated tests to account for skipLines and headers options

### PR DESCRIPTION
**Pull request by combizs**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [x] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### CODE REVIEW

**Comment by toddheslin** [comment]
Any update on merging this PR? I've just come across this issue on my side too.

**Comment by combizs** [comment]
@shellscape, have you had a chance to look at this?

**Comment by thevine** [comment]
This needs to be fixed. Any update please?

**Comment by combizs** [comment]
If it doesn’t get merged, you can also check-out the [csv-parse](https://github.com/adaltas/node-csv-parse) module.

**Comment by shellscape** [comment]
Implemented in ead4c1f3a14dbdad961231f3685307e78a03b07e, with credit.

**Pull request closed without merging**
