### PR TITLE
refactor: drop through2

### PR DESCRIPTION
**Pull request by TrySound**
This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### Please Describe Your Changes

Ref https://github.com/rvagg/through2#do-you-need-this
Closes https://github.com/mafintosh/csv-parser/pull/177

Builtin stream.Transform work well on node 8+.

### CODE REVIEW

**Comment by TrySound** [comment]
@contra Will this work for you?

**Comment by TrySound** [comment]
cc @mafintosh

**Comment by contra** [comment]
@TrySound I think this is fine, however it is recommended to use `readable-stream` instead of the node core stream module to avoid all sorts of issues between node versions (see the `readable-stream` README for more explanation).

**Comment by shellscape** [comment]
I don't think we need to use the userland streams package. Mostly because Node v8 is out of LTS and no longer supported. @TrySound I'd say this is good as-is if we raise the minimum Node version to an LTS version.

**Comment by TrySound** [comment]
Done. Bumped node support.

**Pull request merged**
