### PR TITLE
Replace buffer constructor with buffer-alloc and buffer-from

### PR DESCRIPTION
**Pull request by jasnell**

### CODE REVIEW

**Comment by mafintosh** [comment]
1.12.1

**Comment by caub** [comment]
@jasnell just wondering, why not `Buffer.from` ? do you still need node 0.12 and less support (which are EOL anyway)

**Comment by mafintosh** [comment]
Buffer.from means major bump. Too many dependents would be affected by that

**Comment by jimmywarting** [comment]
Time to switch to using Buffer.from now? it's 2020 now

**Pull request merged**
